correct auto compilation of ffw3, superlu, tetgen in cas au enable-download

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar RANLIB ac_ct_RANLIB MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 FLIBS CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LEX LEXLIB LEX_OUTPUT_ROOT YACC WINDRESOBJ LIBSNOCONSOLE WIN32DLLTARGET ff_prefix_dir OPTIM_TYPE ADD_PACKAGE_NAME CXXCPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS X11_LIBS EGREP LIBSGLUT LIBSPTHREAD ff_mpirun MPIPROG MPICXX ff_wget ff_curl WGET ff_unzip GENERIC_BLAS GENERIC_BLAS_BUILT_SOURCES DOWNLOAD_BLAS BLASLIBS BLASINC G2CLIB DOWNLOAD_ARPACK FF_LAPACKdir ARPACKLIB LAPACKLIB ARPACKLIBS EIGENTEST EIGENOBJ DOWNLOAD_UMFPACK FF_UMFPACK_CONFIG UMFPACKLIBS FF_SECOND ff_libtool STATICTOOL AR ARFLAGS RANLIN LOAD_TESTS LOAD_COMPILE DYLIB_SUFFIX ff_latex ff_makeindex ff_dvips ff_pdf2ps EPSTOPDF ff_convert DOCPS ff_gzip DOCPSGZ ff_pdflatex DOCPDF ff_history HISTORY STD_GRAPH_OBJ STD_LDFLAGS STD_LIBS ff_fltk DOWNLOAD_FLTK FLTK_VERSION FLTK_CONFIG_PARAM FLTK_CONFIG IDE_LIBS FLTK_XONLY KERNEL_VERSION LIBC_VERSION MEDITPROG FFGLUTPROG BAMGPROG GLXPROG STDPROG AGLPROG X11PROG IDEPROG TESTIDEPROG IDE_TESTS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar RANLIB ac_ct_RANLIB MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 FLIBS CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LEX LEXLIB LEX_OUTPUT_ROOT YACC WINDRESOBJ LIBSNOCONSOLE WIN32DLLTARGET ff_prefix_dir OPTIM_TYPE ADD_PACKAGE_NAME CXXCPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS X11_LIBS EGREP LIBSGLUT LIBSPTHREAD ff_mpirun MPIPROG MPICXX ff_wget ff_curl WGET DOWNLOADCOMPILE ff_unzip GENERIC_BLAS GENERIC_BLAS_BUILT_SOURCES DOWNLOAD_BLAS BLASLIBS BLASINC G2CLIB DOWNLOAD_ARPACK FF_LAPACKdir ARPACKLIB LAPACKLIB ARPACKLIBS EIGENTEST EIGENOBJ DOWNLOAD_UMFPACK FF_UMFPACK_CONFIG UMFPACKLIBS FF_SECOND ff_libtool STATICTOOL AR ARFLAGS RANLIN LOAD_TESTS LOAD_COMPILE DYLIB_SUFFIX ff_latex ff_makeindex ff_dvips ff_pdf2ps EPSTOPDF ff_convert DOCPS ff_gzip DOCPSGZ ff_pdflatex DOCPDF ff_history HISTORY STD_GRAPH_OBJ STD_LDFLAGS STD_LIBS ff_fltk DOWNLOAD_FLTK FLTK_VERSION FLTK_CONFIG_PARAM FLTK_CONFIG IDE_LIBS FLTK_XONLY KERNEL_VERSION LIBC_VERSION MEDITPROG FFGLUTPROG BAMGPROG GLXPROG STDPROG AGLPROG X11PROG IDEPROG TESTIDEPROG IDE_TESTS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -11198,7 +11198,7 @@ fi
 # if enabling downloads find wget or curl to do download
 # ------------------------------------------------------
 
-if test  "$ff_wget" =  no -a "$enable_download" = yes
+if test  "$ff_wget" =  no
 then
 	ff_wget=""
 	# Extract the first word of "wget", so it can be a program name with args.
@@ -11238,7 +11238,7 @@ echo "${ECHO_T}no" >&6
 fi
 
 fi
-if test  "$ff_wget" = no -a "$enable_download" = yes
+if test  "$ff_wget" = no
 then
         ff_wget_command="curl -O"
   	ff_curl=""
@@ -11281,7 +11281,23 @@ fi
 	ff_wget="$ff_curl"
 fi
 
+# for automatique compilation of
+# lib in download
+if test -z "$ff_wget_command" -a "$enable_download"  = "yes"  ; then
+  enable_download=no
+  { { echo "$as_me:$LINENO: error:    enable-download and no wget or curl. " >&5
+echo "$as_me: error:    enable-download and no wget or curl. " >&2;}
+   { (exit 1); exit 1; }; };
+fi
+if test "$enable_download"  = "yes" ; then
+DOWNLOADCOMPILE=compile
+else
+DOWNLOADCOMPILE=
+fi
+
 WGET=$ff_wget_command
+
+DOWNLOADCOMPILE=$DOWNLOADCOMPILE
 
 
 #  modif FH -----
@@ -15996,6 +16012,7 @@ s,@MPICXX@,$MPICXX,;t t
 s,@ff_wget@,$ff_wget,;t t
 s,@ff_curl@,$ff_curl,;t t
 s,@WGET@,$WGET,;t t
+s,@DOWNLOADCOMPILE@,$DOWNLOADCOMPILE,;t t
 s,@ff_unzip@,$ff_unzip,;t t
 s,@GENERIC_BLAS@,$GENERIC_BLAS,;t t
 s,@GENERIC_BLAS_BUILT_SOURCES@,$GENERIC_BLAS_BUILT_SOURCES,;t t
