-  add in download automatic generation of f2c and fort77 to get a free  fortran compiler         just  go in         (download/f2d;make install)   -  add automatic find of libf2c in case of F77=fort77 (driver of f2c) in configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2612,7 +2612,7 @@ ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f77_compiler_gnu
 if test -n "$ac_tool_prefix"; then
-  for ac_prog in g77 f77 gfortran g77 f90 xlf xlf90 `pwd`/download/bin/fort77
+  for ac_prog in g77 f77 gfortran g77 f90 xlf xlf90 fort77
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -2654,7 +2654,7 @@ fi
 fi
 if test -z "$F77"; then
   ac_ct_F77=$F77
-  for ac_prog in g77 f77 gfortran g77 f90 xlf xlf90 `pwd`/download/bin/fort77
+  for ac_prog in g77 f77 gfortran g77 f90 xlf xlf90 fort77
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -2843,6 +2843,8 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
+#	if test -n "$F77"
+#	then
         ff_flibs=""
         # modif FH
 
@@ -2897,7 +2899,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:2900: \"$ac_link\") >&5
+(eval echo $as_me:2902: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -2975,7 +2977,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:2978: \"$ac_link\") >&5
+(eval echo $as_me:2980: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -3149,7 +3151,13 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 	# correct pb of double def under macos
 	case $F77 in
-	*/download/bin/fort77)  FLIBS="-L`pwd`/download/lib -lf2c";;
+	 *fort77)
+	   if test -z "$FLIBS" ; then
+             FLIBS=`fort77 -v  a.out  2>&1|awk '/a.out/ && /fort77/  { print $(NF-2),$(NF-1)}'`
+             { echo "$as_me:$LINENO: WARNING:   fort77   FLIBS :  $FLIBS " >&5
+echo "$as_me: WARNING:   fort77   FLIBS :  $FLIBS " >&2;}
+	   fi
+	   ;;
 	 *g77)
 	 for i in $FLIBS; do
           case $i in
@@ -3184,6 +3192,29 @@ fi;
 	then
 	  ff_g2c_lib="$with_flib"
 	  FLIBS="$with_flib"
+	fi
+# add FH oct 2007 for download f2c
+	if test -z "$F77"  ; then
+	  ff_f77=`pwd`/download/bin/fort77
+	  ff_flibs=`pwd`/download/lib/libf2c.a
+	  if test -f $ff_f77  -a -f $ff_flibs ; then
+	    { echo "$as_me:$LINENO: WARNING:  no fortran, but find download f2c/fort" >&5
+echo "$as_me: WARNING:  no fortran, but find download f2c/fort" >&2;};
+	    F77=fort77
+	    FLIBS=$ff_flibs
+	   else
+	     { echo "$as_me:$LINENO:  fatal error : no fortran  " >&5
+echo "$as_me:  fatal error : no fortran  " >&6;};
+	     { echo "$as_me:$LINENO: add ---without-fortran   " >&5
+echo "$as_me: add ---without-fortran   " >&6;};
+	     { echo "$as_me:$LINENO: or try to compile f2c in directory download/f2c   " >&5
+echo "$as_me: or try to compile f2c in directory download/f2c   " >&6;};
+	     { echo "$as_me:$LINENO:   just do:  make install  " >&5
+echo "$as_me:   just do:  make install  " >&6;};
+	    { { echo "$as_me:$LINENO: error:  Fatal error No Fortran compiler . " >&5
+echo "$as_me: error:  Fatal error No Fortran compiler . " >&2;}
+   { (exit 1); exit 1; }; };
+	  fi
 	fi
 fi
 
