remove F77_WRAPPER form configure trap on my mac with fort77

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3914,7 +3914,109 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-	ac_ext=c
+	# correct pb of double def under macos
+	case $F77 in
+	 *fort77)
+	   if test -z "$FLIBS" ; then
+#             FLIBS=`fort77 -v  a.out  2>&1|awk '/a.out/ && /fort77/  { print $(NF-2),$(NF-1)}'`
+#  FH to remove " "
+	     FLIBS=`fort77 -v  a.out  2>&1|awk '/a.out/ && /fort77/  { print "echo",$(NF-2),$(NF-1)}'|sh`
+
+             { echo "$as_me:$LINENO: WARNING:   fort77   FLIBS :  $FLIBS " >&5
+echo "$as_me: WARNING:   fort77   FLIBS :  $FLIBS " >&2;}
+	   fi
+	   ;;
+	 *g77)
+	 for i in $FLIBS; do
+          case $i in
+# save last directory of the list
+	   -L*)
+	   d=`expr $i : '-L\(.*\)'`;
+	   echo " try $d "
+	   if test -e "$d/libg2c.so" ; then
+	     ff_flibs="$d/libg2c.so"
+	   elif test -e "$d/libg2c.dylib" ; then
+	     ff_flibs="$d/libg2c.dylib"
+	   elif test -e "$d/libg2c.a" ; then
+	     ff_flibs="$d/libg2c.a"
+	   elif test  -e $d/libg2c.so -o	-e $d/libg2c.a ; then
+	      ff_flibs="$i"
+	   fi;;
+          esac
+	 done
+	 if test -e "$ff_flibs"  ;then
+          FLIBS="$ff_flibs"
+	 else
+	  FLIBS="$ff_flibs -lg2c"
+	 fi
+	 { echo "$as_me:$LINENO: WARNING:   get dir of -lg2c  FLIBS :  $FLIBS " >&5
+echo "$as_me: WARNING:   get dir of -lg2c  FLIBS :  $FLIBS " >&2;}
+	 ;;
+# add FH sep 2006 / modif  2009
+         *gfortran)
+         for i in $FLIBS; do
+          case $i in
+           -L*)
+	   d=`expr $i : '-L\(.*\)'`;
+	   if test -e "$d/libgfortran.so" ; then
+	     ff_flibs="$d/libgfortran.so"
+	   elif test -e "$d/libgfortran.dylib" ; then
+	     ff_flibs="$d/libgfortran.dylib"
+	   elif test -e "$d/libgfortran.a" ; then
+	     ff_flibs="$d/libgfortran.a"
+	   elif test -e $d/libgfortran.so -o -e $d/libgfortran.a -o -e $d/libgfortran.dylib ; then
+	      ff_flibs="$i"
+	   fi;;
+          esac
+         done
+	 if test -e "$ff_flibs"  ;then
+          FLIBS="$ff_flibs"
+	 else
+         FLIBS="$ff_flibs -lgfortran"
+	 fi
+         { echo "$as_me:$LINENO: WARNING:   get dir of -lgfortran  FLIBS :  $FLIBS " >&5
+echo "$as_me: WARNING:   get dir of -lgfortran  FLIBS :  $FLIBS " >&2;}
+         ;;
+	esac
+
+# Check whether --with-flib was given.
+if test "${with_flib+set}" = set; then
+  withval=$with_flib;
+fi
+
+#  correct FH sep 2006 -o -> -a
+	if test "$with_flib" != no -a -n  "$with_flib"
+	then
+	  ff_g2c_lib="$with_flib"
+	  FLIBS="$with_flib"
+	fi
+# add FH oct 2007 for download f2c
+	if test -z "$F77"  ; then
+	  ff_f77=`pwd`/download/bin/fort77
+	  ff_flibs=`pwd`/download/lib/libf2c.a
+	  if test -x $ff_f77  -a -f $ff_flibs ; then
+	    { echo "$as_me:$LINENO: WARNING:  no fortran, but find download f2c/fort" >&5
+echo "$as_me: WARNING:  no fortran, but find download f2c/fort" >&2;};
+	    F77=$ff_f77
+	    FLIBS=$ff_flibs
+	   else
+	     { echo "$as_me:$LINENO:  fatal error : no fortran  " >&5
+echo "$as_me:  fatal error : no fortran  " >&6;};
+	     { echo "$as_me:$LINENO: add ---without-fortran   " >&5
+echo "$as_me: add ---without-fortran   " >&6;};
+	     { echo "$as_me:$LINENO: or try to compile f2c in directory download/f2c   " >&5
+echo "$as_me: or try to compile f2c in directory download/f2c   " >&6;};
+	     { echo "$as_me:$LINENO:   just do:  make install  " >&5
+echo "$as_me:   just do:  make install  " >&6;};
+	    { { echo "$as_me:$LINENO: error:  Fatal error No Fortran compiler . " >&5
+echo "$as_me: error:  Fatal error No Fortran compiler . " >&2;}
+   { (exit 1); exit 1; }; };
+	  fi
+	fi
+#  check if the FLIBS is correct
+  ff_libs="$LIBS"
+  LIBS="$ff_libs $FLIBS"
+  ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -4272,14 +4374,6 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-#ifdef F77_DUMMY_MAIN
-
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-
-#endif
 int
 main ()
 {
@@ -4341,14 +4435,6 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-#ifdef F77_DUMMY_MAIN
-
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-
-#endif
 int
 main ()
 {
@@ -4387,14 +4473,6 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-#ifdef F77_DUMMY_MAIN
-
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-
-#endif
 int
 main ()
 {
@@ -4434,14 +4512,6 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-#ifdef F77_DUMMY_MAIN
-
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-
-#endif
 int
 main ()
 {
@@ -4557,14 +4627,6 @@ struct s2 {int (*f) (double a);};
 int pairnames (int, char **, FILE *(*)(struct buf *, struct stat *, int), int, int);
 int argc;
 char **argv;
-#ifdef F77_DUMMY_MAIN
-
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-
-#endif
 int
 main ()
 {
@@ -4739,7 +4801,135 @@ fi
 
 
 
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char exit ();
+int
+main ()
+{
+return exit ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ff_err=
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ff_err=ok
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext;
+  if test "$ff_err" = "ok" ; then  { { echo "$as_me:$LINENO: error:  Fatal FLIBS: $FLIBS is incorrect. " >&5
+echo "$as_me: error:  Fatal FLIBS: $FLIBS is incorrect. " >&2;}
+   { (exit 1); exit 1; }; }; fi
+  LIBS="$ff_libs"
+  echo "F77 LD $ff_libs" >config_LIB_INFO
+
+  { echo "$as_me:$LINENO: checking  Size of fortran 77 integer " >&5
+echo $ECHO_N "checking  Size of fortran 77 integer ... $ECHO_C" >&6; }
+
+
+
+##   AC_LANG(fortran);
 ac_ext=f
+ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
+ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_f77_compiler_gnu
+
+ if test "$cross_compiling" = yes; then
+  ff_f77intsize=4
+else
+  cat >conftest.$ac_ext <<_ACEOF
+
+      program test
+      integer  p,i
+      p=1024*1024
+      i= p*p
+      open(7,file="conftest.out")
+      if (i>0) then
+         write(7,*) 8
+      else
+         write(7,*) 4
+      endif
+      close(7)
+      end
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ff_f77intsize=`cat conftest.out`
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ff_f77intsize=4
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+## AC_LANG(C++)
+ ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+ { echo "$as_me:$LINENO: result: $ff_f77intsize" >&5
+echo "${ECHO_T}$ff_f77intsize" >&6; }
+ ac_ext=f
 ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f77_compiler_gnu
@@ -5150,335 +5340,6 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 ac_ext=f
-ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
-ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_f77_compiler_gnu
-
-
-case $ac_cv_f77_mangling in
-  "lower case, no underscore, no extra underscore")
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC(name,NAME) name
-_ACEOF
-
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC_(name,NAME) name
-_ACEOF
- ;;
-  "lower case, no underscore, extra underscore")
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC(name,NAME) name
-_ACEOF
-
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC_(name,NAME) name ## _
-_ACEOF
- ;;
-  "lower case, underscore, no extra underscore")
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC(name,NAME) name ## _
-_ACEOF
-
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC_(name,NAME) name ## _
-_ACEOF
- ;;
-  "lower case, underscore, extra underscore")
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC(name,NAME) name ## _
-_ACEOF
-
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC_(name,NAME) name ## __
-_ACEOF
- ;;
-  "upper case, no underscore, no extra underscore")
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC(name,NAME) NAME
-_ACEOF
-
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC_(name,NAME) NAME
-_ACEOF
- ;;
-  "upper case, no underscore, extra underscore")
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC(name,NAME) NAME
-_ACEOF
-
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC_(name,NAME) NAME ## _
-_ACEOF
- ;;
-  "upper case, underscore, no extra underscore")
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC(name,NAME) NAME ## _
-_ACEOF
-
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC_(name,NAME) NAME ## _
-_ACEOF
- ;;
-  "upper case, underscore, extra underscore")
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC(name,NAME) NAME ## _
-_ACEOF
-
-          cat >>confdefs.h <<\_ACEOF
-#define F77_FUNC_(name,NAME) NAME ## __
-_ACEOF
- ;;
-  *)
-          { echo "$as_me:$LINENO: WARNING: unknown Fortran name-mangling scheme" >&5
-echo "$as_me: WARNING: unknown Fortran name-mangling scheme" >&2;}
-          ;;
-esac
-
-ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
-	# correct pb of double def under macos
-	case $F77 in
-	 *fort77)
-	   if test -z "$FLIBS" ; then
-#             FLIBS=`fort77 -v  a.out  2>&1|awk '/a.out/ && /fort77/  { print $(NF-2),$(NF-1)}'`
-#  FH to remove " "
-	     FLIBS=`fort77 -v  a.out  2>&1|awk '/a.out/ && /fort77/  { print "echo",$(NF-2),$(NF-1)}'|sh`
-
-             { echo "$as_me:$LINENO: WARNING:   fort77   FLIBS :  $FLIBS " >&5
-echo "$as_me: WARNING:   fort77   FLIBS :  $FLIBS " >&2;}
-	   fi
-	   ;;
-	 *g77)
-	 for i in $FLIBS; do
-          case $i in
-# save last directory of the list
-	   -L*)
-	   d=`expr $i : '-L\(.*\)'`;
-	   echo " try $d "
-	   if test -e "$d/libg2c.so" ; then
-	     ff_flibs="$d/libg2c.so"
-	   elif test -e "$d/libg2c.dylib" ; then
-	     ff_flibs="$d/libg2c.dylib"
-	   elif test -e "$d/libg2c.a" ; then
-	     ff_flibs="$d/libg2c.a"
-	   elif test  -e $d/libg2c.so -o	-e $d/libg2c.a ; then
-	      ff_flibs="$i"
-	   fi;;
-          esac
-	 done
-	 if test -e "$ff_flibs"  ;then
-          FLIBS="$ff_flibs"
-	 else
-	  FLIBS="$ff_flibs -lg2c"
-	 fi
-	 { echo "$as_me:$LINENO: WARNING:   get dir of -lg2c  FLIBS :  $FLIBS " >&5
-echo "$as_me: WARNING:   get dir of -lg2c  FLIBS :  $FLIBS " >&2;}
-	 ;;
-# add FH sep 2006 / modif  2009
-         *gfortran)
-         for i in $FLIBS; do
-          case $i in
-           -L*)
-	   d=`expr $i : '-L\(.*\)'`;
-	   if test -e "$d/libgfortran.so" ; then
-	     ff_flibs="$d/libgfortran.so"
-	   elif test -e "$d/libgfortran.dylib" ; then
-	     ff_flibs="$d/libgfortran.dylib"
-	   elif test -e "$d/libgfortran.a" ; then
-	     ff_flibs="$d/libgfortran.a"
-	   elif test -e $d/libgfortran.so -o -e $d/libgfortran.a -o -e $d/libgfortran.dylib ; then
-	      ff_flibs="$i"
-	   fi;;
-          esac
-         done
-	 if test -e "$ff_flibs"  ;then
-          FLIBS="$ff_flibs"
-	 else
-         FLIBS="$ff_flibs -lgfortran"
-	 fi
-         { echo "$as_me:$LINENO: WARNING:   get dir of -lgfortran  FLIBS :  $FLIBS " >&5
-echo "$as_me: WARNING:   get dir of -lgfortran  FLIBS :  $FLIBS " >&2;}
-         ;;
-	esac
-
-# Check whether --with-flib was given.
-if test "${with_flib+set}" = set; then
-  withval=$with_flib;
-fi
-
-#  correct FH sep 2006 -o -> -a
-	if test "$with_flib" != no -a -n  "$with_flib"
-	then
-	  ff_g2c_lib="$with_flib"
-	  FLIBS="$with_flib"
-	fi
-# add FH oct 2007 for download f2c
-	if test -z "$F77"  ; then
-	  ff_f77=`pwd`/download/bin/fort77
-	  ff_flibs=`pwd`/download/lib/libf2c.a
-	  if test -x $ff_f77  -a -f $ff_flibs ; then
-	    { echo "$as_me:$LINENO: WARNING:  no fortran, but find download f2c/fort" >&5
-echo "$as_me: WARNING:  no fortran, but find download f2c/fort" >&2;};
-	    F77=$ff_f77
-	    FLIBS=$ff_flibs
-	   else
-	     { echo "$as_me:$LINENO:  fatal error : no fortran  " >&5
-echo "$as_me:  fatal error : no fortran  " >&6;};
-	     { echo "$as_me:$LINENO: add ---without-fortran   " >&5
-echo "$as_me: add ---without-fortran   " >&6;};
-	     { echo "$as_me:$LINENO: or try to compile f2c in directory download/f2c   " >&5
-echo "$as_me: or try to compile f2c in directory download/f2c   " >&6;};
-	     { echo "$as_me:$LINENO:   just do:  make install  " >&5
-echo "$as_me:   just do:  make install  " >&6;};
-	    { { echo "$as_me:$LINENO: error:  Fatal error No Fortran compiler . " >&5
-echo "$as_me: error:  Fatal error No Fortran compiler . " >&2;}
-   { (exit 1); exit 1; }; };
-	  fi
-	fi
-#  check if the FLIBS is correct
-  ff_libs="$LIBS"
-  LIBS="$ff_libs $FLIBS"
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char exit ();
-#ifdef F77_DUMMY_MAIN
-
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-
-#endif
-int
-main ()
-{
-return exit ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ff_err=
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ff_err=ok
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext;
-  if test "$ff_err" = "ok" ; then  { { echo "$as_me:$LINENO: error:  Fatal FLIBS: $FLIBS is incorrect. " >&5
-echo "$as_me: error:  Fatal FLIBS: $FLIBS is incorrect. " >&2;}
-   { (exit 1); exit 1; }; }; fi
-  LIBS="$ff_libs"
-  echo "F77 LD $ff_libs" >config_LIB_INFO
-
-  { echo "$as_me:$LINENO: checking  Size of fortran 77 integer " >&5
-echo $ECHO_N "checking  Size of fortran 77 integer ... $ECHO_C" >&6; }
-
-
-
-##   AC_LANG(fortran);
-ac_ext=f
-ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
-ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_f77_compiler_gnu
-
- if test "$cross_compiling" = yes; then
-  ff_f77intsize=4
-else
-  cat >conftest.$ac_ext <<_ACEOF
-
-      program test
-      integer  p,i
-      p=1024*1024
-      i= p*p
-      open(7,file="conftest.out")
-      if (i>0) then
-         write(7,*) 8
-      else
-         write(7,*) 4
-      endif
-      close(7)
-      end
-
-_ACEOF
-rm -f conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ff_f77intsize=`cat conftest.out`
-else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-( exit $ac_status )
-ff_f77intsize=4
-fi
-rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
-
-
-## AC_LANG(C++)
- ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
- { echo "$as_me:$LINENO: result: $ff_f77intsize" >&5
-echo "${ECHO_T}$ff_f77intsize" >&6; }
- ac_ext=f
 ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f77_compiler_gnu
