correct the mpi version for macos lam mpi

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar RANLIB ac_ct_RANLIB MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LEX LEXLIB LEX_OUTPUT_ROOT YACC WINDRESOBJ WIN32DLLTARGET OPTIM_TYPE ADD_PACKAGE_NAME X11_LIBS CXXCPP EGREP ff_mpirun MPIPROG ff_wget WGET ff_unzip GENERIC_BLAS GENERIC_BLAS_BUILT_SOURCES DOWNLOAD_BLAS BLASLIB BLASINC G2CLIB DOWNLOAD_ARPACK FF_LAPACKdir ARPACKLIB EIGENTEST EIGENOBJ DOWNLOAD_UMFPACK FF_UMFPACK_CONFIG UMFPACKLIB ff_libtool STATICTOOL LOAD_TESTS LOAD_COMPILE DYLIB_SUFFIX ff_latex ff_makeindex ff_dvips ff_pdf2ps ff_epstopdf ff_convert DOCPS ff_gzip DOCPSGZ ff_pdflatex DOCPDF ff_history HISTORY STD_GRAPH_OBJ STD_LDFLAGS STD_LIBS ff_fltk DOWNLOAD_FLTK FLTK_VERSION FLTK_CONFIG_PARAM FLTK_CONFIG IDE_LIBS FLTK_XONLY KERNEL_VERSION LIBC_VERSION GLXPROG AGLPROG X11PROG IDEPROG IDE_TESTS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar RANLIB ac_ct_RANLIB MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LEX LEXLIB LEX_OUTPUT_ROOT YACC WINDRESOBJ WIN32DLLTARGET OPTIM_TYPE ADD_PACKAGE_NAME X11_LIBS CXXCPP EGREP ff_mpirun MPIPROG MPICXX ff_wget WGET ff_unzip GENERIC_BLAS GENERIC_BLAS_BUILT_SOURCES DOWNLOAD_BLAS BLASLIB BLASINC G2CLIB DOWNLOAD_ARPACK FF_LAPACKdir ARPACKLIB EIGENTEST EIGENOBJ DOWNLOAD_UMFPACK FF_UMFPACK_CONFIG UMFPACKLIB FF_SECOND ff_libtool STATICTOOL LOAD_TESTS LOAD_COMPILE DYLIB_SUFFIX ff_latex ff_makeindex ff_dvips ff_pdf2ps ff_epstopdf ff_convert DOCPS ff_gzip DOCPSGZ ff_pdflatex DOCPDF ff_history HISTORY STD_GRAPH_OBJ STD_LDFLAGS STD_LIBS ff_fltk DOWNLOAD_FLTK FLTK_VERSION FLTK_CONFIG_PARAM FLTK_CONFIG IDE_LIBS FLTK_XONLY KERNEL_VERSION LIBC_VERSION GLXPROG AGLPROG X11PROG IDEPROG IDE_TESTS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -888,7 +888,7 @@ Optional Packages:
   --with-flib= the fortran library
   --with-suffix=G3/G4/G4,P4,.. or --without-suffix (default no suffix to package name)
   --with-suffix=G3/G4/G4,P4,.. or --without-suffix (default no suffix package name)
-  --with-mpi=mpich/lam/yes/no	or --without-mpi	Choose MPI implementation (default is mpich)
+  --with-mpi=yes/no/mpiCC /mpic++/... 	or --without-mpi	Choose MPI implementation (default is mpich)
   --with-wget=command	Replace "wget" with another command. Implies --enable-download
   --with-blas=library	Use a specific version of the Blas
   --with-arpack=library	Use a specific version of Arpack
@@ -7469,15 +7469,21 @@ fi;
 # Default is mpich
 if test "$with_mpi" = yes
 then
-	with_mpi=mpich
+   ff_mpicxx=mpiCC
+else
+  case "$with_mpi" in
+ lam|mpich)   ff_mpicxx=mpiCC.$with_mpi;;
+ *)  ff_mpicxx="$with_mpi" ;;
+ esac
 fi
 
 if test "$with_mpi" != no
 then
-	echo "$as_me:$LINENO: checking for mpiCC.$with_mpi" >&5
-echo $ECHO_N "checking for mpiCC.$with_mpi... $ECHO_C" >&6
+
+	echo "$as_me:$LINENO: checking for $ff_mpicxx" >&5
+echo $ECHO_N "checking for $ff_mpicxx... $ECHO_C" >&6
 	ff_save_cxx="$CXX"
-	CXX=mpiCC.$with_mpi
+	CXX=$ff_mpicxx
 	cat >conftest.$ac_ext <<_ACEOF
 #include <stdio.h>
 #include <mpi.h>
@@ -7580,8 +7586,159 @@ fi
 		# We do not AC_DEFINE any special flag for parallel
 		# computation here, because it must only be set when the
 		# parallel program is compiled (see src/mpi/Makfile.am)
+                if test "${ac_cv_header_mpicxx_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for mpicxx.h" >&5
+echo $ECHO_N "checking for mpicxx.h... $ECHO_C" >&6
+if test "${ac_cv_header_mpicxx_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_mpicxx_h" >&5
+echo "${ECHO_T}$ac_cv_header_mpicxx_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking mpicxx.h usability" >&5
+echo $ECHO_N "checking mpicxx.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <mpicxx.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking mpicxx.h presence" >&5
+echo $ECHO_N "checking mpicxx.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <mpicxx.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: mpicxx.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: mpicxx.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpicxx.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: mpicxx.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: mpicxx.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: mpicxx.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpicxx.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: mpicxx.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpicxx.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: mpicxx.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpicxx.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: mpicxx.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpicxx.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: mpicxx.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpicxx.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: mpicxx.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ----------------------------------- ##
+## Report this to hecht@ann.jussieu.fr ##
+## ----------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for mpicxx.h" >&5
+echo $ECHO_N "checking for mpicxx.h... $ECHO_C" >&6
+if test "${ac_cv_header_mpicxx_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_mpicxx_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_mpicxx_h" >&5
+echo "${ECHO_T}$ac_cv_header_mpicxx_h" >&6
+
+fi
+if test $ac_cv_header_mpicxx_h = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MPICXX_H 1
+_ACEOF
+
+fi
+
+
 
 		MPIPROG=FreeFem++-mpi${EXEEXT}
+
+                MPICXX=$ff_mpicxx
+
+	else
+	        MPICXX=$ff_save_cxx
 
 	fi
 fi
@@ -8301,6 +8458,8 @@ rm -f conftest.err conftest.$ac_objext \
 echo "${ECHO_T}$ff_blas_ok" >&6
 fi
 done
+
+
 
 
 # If all else fails, download!
@@ -9704,6 +9863,113 @@ _ACEOF
 
 fi
 done
+
+
+
+for ac_func in second_
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+ ff_second=""
+else
+  ff_second=second.o
+fi
+done
+
+FF_SECOND="$ff_second"
 
 
 # If times() and sysconf() are not here, UMFPACK should know
@@ -11540,6 +11806,7 @@ s,@CXXCPP@,$CXXCPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@ff_mpirun@,$ff_mpirun,;t t
 s,@MPIPROG@,$MPIPROG,;t t
+s,@MPICXX@,$MPICXX,;t t
 s,@ff_wget@,$ff_wget,;t t
 s,@WGET@,$WGET,;t t
 s,@ff_unzip@,$ff_unzip,;t t
@@ -11557,6 +11824,7 @@ s,@EIGENOBJ@,$EIGENOBJ,;t t
 s,@DOWNLOAD_UMFPACK@,$DOWNLOAD_UMFPACK,;t t
 s,@FF_UMFPACK_CONFIG@,$FF_UMFPACK_CONFIG,;t t
 s,@UMFPACKLIB@,$UMFPACKLIB,;t t
+s,@FF_SECOND@,$FF_SECOND,;t t
 s,@ff_libtool@,$ff_libtool,;t t
 s,@STATICTOOL@,$STATICTOOL,;t t
 s,@LOAD_TESTS@,$LOAD_TESTS,;t t
