Dynamic loading is now disabled if dlopen() does not link properly (bug reported by Haiko Etzel)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9619,14 +9619,9 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "${ECHO_T}$ff_dynload" >&6
 fi
 
-#  the -rdynamic don't exist on macos
-if test "$ff_dynload" = yes  ;
+# Checks that we also have the corresponding library
+if test "$ff_dynload" = yes
 then
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_DLFCN_H 1
-_ACEOF
-
 
 echo "$as_me:$LINENO: checking for dlinfo in -ldl" >&5
 echo $ECHO_N "checking for dlinfo in -ldl... $ECHO_C" >&6
@@ -9699,6 +9694,59 @@ _ACEOF
   LIBS="-ldl $LIBS"
 
 fi
+
+
+	# Checks that everythings works ok
+	echo "$as_me:$LINENO: checking whether dlopen links ok" >&5
+echo $ECHO_N "checking whether dlopen links ok... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+#include <dlfcn.h>
+int main(int argc,char **argv){
+  dlopen("",RTLD_LAZY);
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ff_dynload=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ff_dynload=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	echo "$as_me:$LINENO: result: $ff_dynload" >&5
+echo "${ECHO_T}$ff_dynload" >&6
+fi
+
+#  the -rdynamic don't exist on macos
+if test "$ff_dynload" = yes
+then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DLFCN_H 1
+_ACEOF
 
 
 	# Activate dynamic loading tests (see examples++-load/Makefile.am)
